### ISSUE TITLE
Special characters used in particle names not rendering in Excel

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#58] opened 2024-07-31 15:55 UTC
Special characters from saved .csv files render correctly in basic text editors, but not in Excel.
Investigate.

**Comment by palvarezc** [comment] 2024-08-07 12:54
Closing this as we decided it is not a bug, but rather related on default behaviour from Excel. 

Will add information to the lab manual that will help the users to obtain correctly rendered symbols (#73).

**Closed** 2024-08-07 12:54 UTC
Labels: bug
