### ISSUE TITLE
When exiting window without calculating the magnification parameters, an error is passed.

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#55] opened 2024-07-31 15:31 UTC
This doesn't affect functionality as far as I'm aware. Can probably leave unresolved unless it affects values in the table (yet to test this).

Error msg:
```
AttributeError     Traceback (most recent call last)
File ~\Desktop\Particle Tracks\cavendish-particle-tracks\src\cavendish_particle_tracks\_magnification_dialog.py:182, in MagnificationDialog.accept(self=<cavendish_particle_tracks._magnification_dialog.MagnificationDialog object>)
    179 """On accept propagate the calibration information to the main window and remove the points_Calibration layer"""
    181 print("Propagating magnification to table.")
--> 182 self.parent._propagate_magnification(self.a, self.b)
        self.parent = <cavendish_particle_tracks._widget.ParticleTracksWidget object at 0x0000016E8C5FEE60>
        self = <cavendish_particle_tracks._magnification_dialog.MagnificationDialog object at 0x0000016E90EDC8B0>
```

**Comment by samcunliffe** [comment] 2024-09-29 11:34
Cannot reproduce the `AttributeError` on current `HEAD` of `main`. Possibly it was fixed elsewhere or made obsolete by some other fix.

https://github.com/user-attachments/assets/4849bec0-d46e-4ec6-a210-13318f873074


Closing as cannot reproduce. Reopen if this reappears or is reintroduced.

**Closed by samcunliffe** 2024-09-29 11:34 UTC
Labels: bug, enhancement
